name: 'dbt_training'
version: '1.0.0'
config-version: 2 

profile: 'default'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

vars:
  Jaffle_shop:
    customerid: 50
    
models:
  dbt_training:
    QWT:
      database: QWT_ANALYTICS
    # Applies to all files under models/example/
    example:
      materialized: view
    jaffle_shop:
      materialized: view
      
seeds:
  jaffle_shop:
    schema: seed_data
